// Service Worker — generated by NeoCode
importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-auth-compat.js'); // 🚀 إجبارية للمصادقة بالخلفية
importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-database-compat.js'); // 🚀 إجبارية لقاعدة البيانات بالخلفية
importScripts('https://www.gstatic.com/firebasejs/10.12.2/firebase-messaging-compat.js');

let firebaseConfig;
if (self.location.hostname === "neonchat.mooo.com") {
  firebaseConfig = {
    apiKey: "AIzaSyCZH225ITSw_JGx8Faq8nxxgzb49SBqrk8",
    authDomain: "neonchat-2df05.firebaseapp.com",
    databaseURL: "https://neonchat-2df05-default-rtdb.firebaseio.com",
    projectId: "neonchat-2df05",
    storageBucket: "neonchat-2df05.firebasestorage.app",
    messagingSenderId: "275702671868",
    appId: "1:275702671868:web:e4235a6991b3ae22276a79"
  };
} else {
  firebaseConfig = {
    apiKey: "AIzaSyBB_U4C880PW4GxZd8FALv8yBSiP2mNeBY",
    authDomain: "malaboushi.firebaseapp.com",
    databaseURL: "https://malaboushi-default-rtdb.firebaseio.com/",
    projectId: "malaboushi",
    storageBucket: "malaboushi.firebasestorage.app",
    messagingSenderId: "110336819350",
    appId: "1:110336819350:web:2b1b0488e72b811f0602b7"
  };
}

firebase.initializeApp(firebaseConfig);
const messaging = firebase.messaging();
const db = firebase.database();
const auth = firebase.auth();

// 🚀 محرك الاستلام الحقيقي (True Delivery Receipt) متل الواتساب
// هذا الحدث يستيقظ فور وصول الإشعار للهاتف، حتى لو كان التطبيق مغلقاً تماماً
self.addEventListener('push', function(event) {
  let payload = {};
  try { payload = event.data.json(); } catch(e) {}
  
  // سحب اسم المرسل من الإشعار القادم من Vercel
  const senderName = payload?.notification?.title || payload?.data?.title;
  if (!senderName) return;

  // إبقاء الـ Service Worker حياً حتى تنتهي عملية تحديث قاعدة البيانات
  event.waitUntil(
    new Promise((resolve) => {
      const unsubscribe = auth.onAuthStateChanged(user => {
        if (user) {
          unsubscribe(); // إيقاف الاستماع بمجرد أخذ المستخدم
          
          // 1. البحث عن المحادثة بناءً على اسم المرسل
          db.ref('userChats/' + user.uid).once('value').then(snap => {
            let targetChatId = null;
            snap.forEach(child => {
              if (child.val().friendName === senderName) {
                targetChatId = child.key;
              }
            });

            if (targetChatId) {
              // 2. الدخول للمحادثة وقلب الرسائل إلى "تم الاستلام" (delivered: true)
              db.ref('chats/' + targetChatId + '/messages').orderByKey().limitToLast(15).once('value').then(msgSnap => {
                let updates = {};
                msgSnap.forEach(msgChild => {
                  const m = msgChild.val();
                  // التأكد من أن الرسالة ليست لي ولم تُقرأ ولم تُستلم بعد
                  if (m.senderUid !== user.uid && !m.read && !m.delivered) {
                    updates[msgChild.key + '/delivered'] = true;
                  }
                });
                if (Object.keys(updates).length > 0) {
                  db.ref('chats/' + targetChatId + '/messages').update(updates).then(resolve).catch(resolve);
                } else {
                  resolve();
                }
              }).catch(resolve);
            } else {
              resolve();
            }
          }).catch(resolve);
        }
      });
      
      // مهلة أمان لإنهاء العملية حتى لا يطول تعليق الـ Service Worker
      setTimeout(() => {
        try { unsubscribe(); } catch(e){}
        resolve();
      }, 5000);
    })
  );
});

// تم إزالة onBackgroundMessage لمنع تكرار الإشعارات
// مكتبة Firebase ستقوم الآن بعرض الإشعار الافتراضي بشكل تلقائي ومثالي بناءً على إعدادات Vercel

// رفعنا الإصدار ليجبر المتصفح ياخد النسخة الجديدة (تم رفعه لـ 8 للتأكيد)
const CACHE_NAME = 'app-cache-8'; 
const ASSETS = [
  './',
  './index.html',
  './style.css',
  './script.js',
  './icon.png',
  './manifest.json',
  // ضفنا مكاتب فايربيز لهون مشان يفتح التطبيق ويفوت عالمحادثات بدون نت
  'https://www.gstatic.com/firebasejs/10.12.2/firebase-app-compat.js',
  'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth-compat.js',
  'https://www.gstatic.com/firebasejs/10.12.2/firebase-database-compat.js',
  'https://www.gstatic.com/firebasejs/10.12.2/firebase-storage-compat.js',
  'https://www.gstatic.com/firebasejs/10.12.2/firebase-messaging-compat.js'
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(
      ASSETS.filter(url => !url.includes('icon.png'))
    ))
  );
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE_NAME && k !== 'media-cache').map(k => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', event => {
	  if (event.request.method !== 'GET') return;
	
  // 1. استثناء اتصالات سيرفر فيرسيل بس
  if (event.request.url.includes('vercel.app')) {
    return;
  }

  // 2. تكييش الصوتيات والصور من كلاوديناري مباشرة للعمل بدون نت
  if (event.request.url.includes('cloudinary.com')) {
    event.respondWith(
      caches.match(event.request).then(cached => {
        if (cached) return cached;
        return fetch(event.request).then(response => {
          const clone = response.clone();
          caches.open('media-cache').then(cache => cache.put(event.request, clone));
          return response;
        }).catch(() => {});
      })
    );
    return;
  }

  // 3. باقي الملفات (بما فيها فايربيز)
  event.respondWith(
    caches.match(event.request).then(cached => {
      if (cached) return cached;
      return fetch(event.request).then(response => {
        // شلنا شرط type !== basic لحتى يقبل مكاتب فايربيز الخارجية
        if (!response || response.status !== 200) return response;
        const clone = response.clone();
        caches.open(CACHE_NAME).then(cache => cache.put(event.request, clone));
        return response;
      }).catch(() => caches.match('./index.html'));
    })
  );
});
